-- Section 1200: migrate plaintext aliases to encrypted alias storage

do $$
begin
    if exists (select 1 from public.secret_aliases) then
        raise exception 'secret_aliases_migration_requires_empty_table'
            using errcode = '55000';
    end if;
end;
$$;

drop policy if exists secret_aliases_select_own on public.secret_aliases;
drop function if exists public.rpc_create_secret_alias(uuid, uuid, text, text);

alter table public.secret_aliases
    drop constraint if exists secret_aliases_owner_alias_unique,
    drop column alias,
    drop column alias_normalized,
    alter column created_at drop default,
    alter column id drop default,
    add column alias_ciphertext bytea not null,
    add column alias_nonce bytea not null,
    add column alias_key_version integer not null,
    add column alias_fingerprint bytea not null,
    add column alias_fingerprint_key_version integer not null,
    add column alias_fingerprint_schema_version integer not null,
    add column aad_context jsonb not null,
    add column updated_at timestamptz not null default now(),
    add constraint secret_aliases_alias_ciphertext_not_empty
        check (octet_length(alias_ciphertext) > 0),
    add constraint secret_aliases_alias_nonce_length
        check (octet_length(alias_nonce) = 24),
    add constraint secret_aliases_alias_key_version_positive
        check (alias_key_version > 0),
    add constraint secret_aliases_alias_fingerprint_length
        check (octet_length(alias_fingerprint) = 32),
    add constraint secret_aliases_alias_fingerprint_key_version_positive
        check (alias_fingerprint_key_version > 0),
    add constraint secret_aliases_alias_fingerprint_schema_version_supported
        check (alias_fingerprint_schema_version = 1),
    add constraint secret_aliases_aad_context_object
        check (jsonb_typeof(aad_context) = 'object'),
    add constraint secret_aliases_aad_context_required_keys
        check (
            aad_context ?& array[
                'aad_version',
                'alias_key_version',
                'owner_user_id',
                'secret_alias_id',
                'secret_id'
            ]
        ),
    add constraint secret_aliases_aad_context_allowed_keys
        check (
            aad_context - array[
                'aad_version',
                'alias_key_version',
                'owner_user_id',
                'secret_alias_id',
                'secret_id'
            ] = '{}'::jsonb
        ),
    add constraint secret_aliases_aad_context_matches_row
        check (
            jsonb_typeof(aad_context -> 'aad_version') = 'number'
            and jsonb_typeof(aad_context -> 'alias_key_version') = 'number'
            and jsonb_typeof(aad_context -> 'owner_user_id') = 'string'
            and jsonb_typeof(aad_context -> 'secret_alias_id') = 'string'
            and jsonb_typeof(aad_context -> 'secret_id') = 'string'
            and aad_context ->> 'aad_version' = '1'
            and aad_context ->> 'secret_alias_id' = id::text
            and aad_context ->> 'secret_id' = secret_id::text
            and aad_context ->> 'owner_user_id' = owner_user_id::text
            and case
                when aad_context ->> 'alias_key_version' ~ '^[1-9][0-9]*$'
                then (aad_context ->> 'alias_key_version')::integer = alias_key_version
                else false
            end
        ),
    add constraint secret_aliases_owner_alias_fingerprint_unique
        unique (owner_user_id, alias_fingerprint),
    add constraint secret_aliases_owner_secret_unique
        unique (owner_user_id, secret_id);

comment on table public.secret_aliases is
    'Encrypted user-defined aliases for secrets. Plaintext alias is never stored and access is limited to SECURITY DEFINER RPCs.';
comment on column public.secret_aliases.id is
    'UUID v4 generated by the SBC and passed via rpc_create_secret_alias.p_secret_alias_id. No DB default; SBC is the sole source of new ids to keep id provenance aligned with secrets.id.';
comment on column public.secret_aliases.secret_id is
    'Canonical secret id. Alias is only a user-facing lookup aid and never replaces the canonical identifier.';
comment on column public.secret_aliases.owner_user_id is
    'Owner scope for alias uniqueness and lookup.';
comment on column public.secret_aliases.alias_ciphertext is
    'XChaCha20-Poly1305 ciphertext of the normalized alias. Plaintext alias is never stored.';
comment on column public.secret_aliases.alias_nonce is
    'XChaCha20-Poly1305 nonce for alias encryption. Must be 24 bytes.';
comment on column public.secret_aliases.alias_key_version is
    'Alias encryption key version bound into aad_context.';
comment on column public.secret_aliases.alias_fingerprint is
    'Owner-scoped deterministic blind index for exact-match alias resolution.';
comment on column public.secret_aliases.alias_fingerprint_key_version is
    'Fingerprint HMAC key version used to derive alias_fingerprint.';
comment on column public.secret_aliases.alias_fingerprint_schema_version is
    'Fingerprint normalization schema version. MVP supports version 1 only.';
comment on column public.secret_aliases.aad_context is
    'Structured alias AAD context with exactly five keys. Decrypt code must rebuild canonical AAD on the SBC.';
comment on column public.secret_aliases.created_at is
    'Timestamp determined by the SBC when constructing the alias record. No DB default is allowed.';
comment on column public.secret_aliases.updated_at is
    'DB-managed mutation timestamp maintained by secret_aliases_set_updated_at.';
comment on constraint secret_aliases_owner_secret_unique on public.secret_aliases is
    'MVP cardinality: 1 secret : 1 alias per owner. Future expansion to 1:N requires dropping this constraint via a forward-only migration. See ADR-0048 and docs/requirements.md (alias) §2.3.';

create trigger secret_aliases_set_updated_at
before update on public.secret_aliases
for each row
execute function public.tg_set_updated_at();

alter table public.secret_aliases enable row level security;
alter table public.secret_aliases force row level security;

revoke all on table public.secret_aliases from anon, authenticated, service_role;

create policy secret_aliases_deny_all
on public.secret_aliases
as restrictive
for all
to public
using (false)
with check (false);

create function public.rpc_create_secret_alias(
    p_request_id uuid,
    p_secret_alias_id uuid,
    p_secret_id uuid,
    p_owner_user_id uuid,
    p_alias_ciphertext bytea,
    p_alias_nonce bytea,
    p_alias_key_version integer,
    p_alias_fingerprint bytea,
    p_alias_fingerprint_key_version integer,
    p_alias_fingerprint_schema_version integer,
    p_aad_context jsonb,
    p_created_at timestamptz
)
returns table (secret_alias_id uuid)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_secret_owner_user_id uuid;
    v_audit_metadata jsonb;
    v_constraint_name text;
begin
    if p_request_id is null
        or p_secret_alias_id is null
        or p_secret_id is null
        or p_owner_user_id is null
        or p_alias_ciphertext is null
        or p_alias_nonce is null
        or p_alias_key_version is null
        or p_alias_fingerprint is null
        or p_alias_fingerprint_key_version is null
        or p_alias_fingerprint_schema_version is null
        or p_aad_context is null
        or p_created_at is null
    then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    if p_secret_alias_id::text !~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        or octet_length(p_alias_ciphertext) = 0
        or octet_length(p_alias_nonce) <> 24
        or p_alias_key_version <= 0
        or octet_length(p_alias_fingerprint) <> 32
        or p_alias_fingerprint_key_version <= 0
        or p_alias_fingerprint_schema_version <> 1
        or jsonb_typeof(p_aad_context) <> 'object'
    then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    if not (
        p_aad_context ?& array[
            'aad_version',
            'alias_key_version',
            'owner_user_id',
            'secret_alias_id',
            'secret_id'
        ]
        and p_aad_context - array[
            'aad_version',
            'alias_key_version',
            'owner_user_id',
            'secret_alias_id',
            'secret_id'
        ] = '{}'::jsonb
        and jsonb_typeof(p_aad_context -> 'aad_version') = 'number'
        and jsonb_typeof(p_aad_context -> 'alias_key_version') = 'number'
        and jsonb_typeof(p_aad_context -> 'owner_user_id') = 'string'
        and jsonb_typeof(p_aad_context -> 'secret_alias_id') = 'string'
        and jsonb_typeof(p_aad_context -> 'secret_id') = 'string'
        and p_aad_context ->> 'aad_version' = '1'
        and p_aad_context ->> 'secret_alias_id' = p_secret_alias_id::text
        and p_aad_context ->> 'secret_id' = p_secret_id::text
        and p_aad_context ->> 'owner_user_id' = p_owner_user_id::text
        and case
            when p_aad_context ->> 'alias_key_version' ~ '^[1-9][0-9]*$'
            then (p_aad_context ->> 'alias_key_version')::integer = p_alias_key_version
            else false
        end
    ) then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    select s.owner_user_id
    into v_secret_owner_user_id
    from public.secrets s
    where s.id = p_secret_id;

    if not found then
        raise exception 'secret_not_found' using errcode = '02000';
    end if;

    if v_secret_owner_user_id <> p_owner_user_id then
        raise exception 'owner_mismatch' using errcode = '42501';
    end if;

    begin
        insert into public.secret_aliases (
            id,
            secret_id,
            owner_user_id,
            alias_ciphertext,
            alias_nonce,
            alias_key_version,
            alias_fingerprint,
            alias_fingerprint_key_version,
            alias_fingerprint_schema_version,
            aad_context,
            created_at
        )
        values (
            p_secret_alias_id,
            p_secret_id,
            p_owner_user_id,
            p_alias_ciphertext,
            p_alias_nonce,
            p_alias_key_version,
            p_alias_fingerprint,
            p_alias_fingerprint_key_version,
            p_alias_fingerprint_schema_version,
            p_aad_context,
            p_created_at
        );
    exception
        when unique_violation then
            get stacked diagnostics v_constraint_name = constraint_name;

            if v_constraint_name in (
                'secret_aliases_owner_alias_fingerprint_unique',
                'secret_aliases_owner_secret_unique'
            ) then
                raise exception 'alias_conflict' using errcode = '23505';
            end if;

            raise;
    end;

    v_audit_metadata := jsonb_build_object(
        'alias_fingerprint',
        encode(p_alias_fingerprint, 'hex'),
        'alias_fingerprint_key_version',
        p_alias_fingerprint_key_version,
        'alias_fingerprint_schema_version',
        p_alias_fingerprint_schema_version
    );

    insert into public.audit_events (
        request_id,
        actor_user_id,
        action,
        target_secret_id,
        result,
        metadata_json
    )
    values (
        p_request_id,
        p_owner_user_id,
        'secret_alias_create',
        p_secret_id,
        'success',
        v_audit_metadata
    );

    return query select p_secret_alias_id;
end;
$$;

create function public.rpc_update_secret_alias(
    p_request_id uuid,
    p_secret_alias_id uuid,
    p_owner_user_id uuid,
    p_alias_ciphertext bytea,
    p_alias_nonce bytea,
    p_alias_key_version integer,
    p_new_alias_fingerprint bytea,
    p_alias_fingerprint_key_version integer,
    p_alias_fingerprint_schema_version integer,
    p_aad_context jsonb
)
returns table (old_alias_fingerprint bytea)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_existing public.secret_aliases%rowtype;
    v_audit_metadata jsonb;
    v_constraint_name text;
begin
    if p_request_id is null
        or p_secret_alias_id is null
        or p_owner_user_id is null
        or p_alias_ciphertext is null
        or p_alias_nonce is null
        or p_alias_key_version is null
        or p_new_alias_fingerprint is null
        or p_alias_fingerprint_key_version is null
        or p_alias_fingerprint_schema_version is null
        or p_aad_context is null
    then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    if p_secret_alias_id::text !~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        or octet_length(p_alias_ciphertext) = 0
        or octet_length(p_alias_nonce) <> 24
        or p_alias_key_version <= 0
        or octet_length(p_new_alias_fingerprint) <> 32
        or p_alias_fingerprint_key_version <= 0
        or p_alias_fingerprint_schema_version <> 1
        or jsonb_typeof(p_aad_context) <> 'object'
    then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    select *
    into v_existing
    from public.secret_aliases sa
    where sa.id = p_secret_alias_id
    for update;

    if not found then
        raise exception 'alias_not_found' using errcode = '02000';
    end if;

    if v_existing.owner_user_id <> p_owner_user_id then
        raise exception 'owner_mismatch' using errcode = '42501';
    end if;

    if not (
        p_aad_context ?& array[
            'aad_version',
            'alias_key_version',
            'owner_user_id',
            'secret_alias_id',
            'secret_id'
        ]
        and p_aad_context - array[
            'aad_version',
            'alias_key_version',
            'owner_user_id',
            'secret_alias_id',
            'secret_id'
        ] = '{}'::jsonb
        and jsonb_typeof(p_aad_context -> 'aad_version') = 'number'
        and jsonb_typeof(p_aad_context -> 'alias_key_version') = 'number'
        and jsonb_typeof(p_aad_context -> 'owner_user_id') = 'string'
        and jsonb_typeof(p_aad_context -> 'secret_alias_id') = 'string'
        and jsonb_typeof(p_aad_context -> 'secret_id') = 'string'
        and p_aad_context ->> 'aad_version' = '1'
        and p_aad_context ->> 'secret_alias_id' = p_secret_alias_id::text
        and p_aad_context ->> 'secret_id' = v_existing.secret_id::text
        and p_aad_context ->> 'owner_user_id' = p_owner_user_id::text
        and case
            when p_aad_context ->> 'alias_key_version' ~ '^[1-9][0-9]*$'
            then (p_aad_context ->> 'alias_key_version')::integer = p_alias_key_version
            else false
        end
    ) then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    begin
        update public.secret_aliases
        set alias_ciphertext = p_alias_ciphertext,
            alias_nonce = p_alias_nonce,
            alias_key_version = p_alias_key_version,
            alias_fingerprint = p_new_alias_fingerprint,
            alias_fingerprint_key_version = p_alias_fingerprint_key_version,
            alias_fingerprint_schema_version = p_alias_fingerprint_schema_version,
            aad_context = p_aad_context
        where id = p_secret_alias_id;
    exception
        when unique_violation then
            get stacked diagnostics v_constraint_name = constraint_name;

            if v_constraint_name = 'secret_aliases_owner_alias_fingerprint_unique' then
                raise exception 'alias_conflict' using errcode = '23505';
            end if;

            raise;
    end;

    v_audit_metadata := jsonb_build_object(
        'old_alias_fingerprint',
        encode(v_existing.alias_fingerprint, 'hex'),
        'new_alias_fingerprint',
        encode(p_new_alias_fingerprint, 'hex'),
        'alias_fingerprint_key_version',
        p_alias_fingerprint_key_version,
        'alias_fingerprint_schema_version',
        p_alias_fingerprint_schema_version
    );

    insert into public.audit_events (
        request_id,
        actor_user_id,
        action,
        target_secret_id,
        result,
        metadata_json
    )
    values (
        p_request_id,
        p_owner_user_id,
        'secret_alias_update',
        v_existing.secret_id,
        'success',
        v_audit_metadata
    );

    return query select v_existing.alias_fingerprint;
end;
$$;

create function public.rpc_delete_secret_alias(
    p_request_id uuid,
    p_secret_alias_id uuid,
    p_owner_user_id uuid
)
returns table (alias_fingerprint bytea)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_existing public.secret_aliases%rowtype;
    v_audit_metadata jsonb;
begin
    if p_request_id is null
        or p_secret_alias_id is null
        or p_owner_user_id is null
    then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    if p_secret_alias_id::text !~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    select *
    into v_existing
    from public.secret_aliases sa
    where sa.id = p_secret_alias_id
    for update;

    if not found then
        raise exception 'alias_not_found' using errcode = '02000';
    end if;

    if v_existing.owner_user_id <> p_owner_user_id then
        raise exception 'owner_mismatch' using errcode = '42501';
    end if;

    delete from public.secret_aliases
    where id = p_secret_alias_id;

    v_audit_metadata := jsonb_build_object(
        'alias_fingerprint',
        encode(v_existing.alias_fingerprint, 'hex'),
        'alias_fingerprint_key_version',
        v_existing.alias_fingerprint_key_version,
        'alias_fingerprint_schema_version',
        v_existing.alias_fingerprint_schema_version
    );

    insert into public.audit_events (
        request_id,
        actor_user_id,
        action,
        target_secret_id,
        result,
        metadata_json
    )
    values (
        p_request_id,
        p_owner_user_id,
        'secret_alias_delete',
        v_existing.secret_id,
        'success',
        v_audit_metadata
    );

    return query select v_existing.alias_fingerprint;
end;
$$;

create function public.rpc_list_secret_aliases(
    p_request_id uuid,
    p_owner_user_id uuid,
    p_limit integer,
    p_offset integer
)
returns table (
    id uuid,
    secret_id uuid,
    alias_ciphertext bytea,
    alias_nonce bytea,
    alias_key_version integer,
    alias_fingerprint bytea,
    alias_fingerprint_key_version integer,
    alias_fingerprint_schema_version integer,
    aad_context jsonb,
    created_at timestamptz,
    updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if p_request_id is null
        or p_owner_user_id is null
        or p_limit is null
        or p_limit <= 0
        or p_limit > 1000
        or p_offset is null
        or p_offset < 0
    then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    return query
    select sa.id,
        sa.secret_id,
        sa.alias_ciphertext,
        sa.alias_nonce,
        sa.alias_key_version,
        sa.alias_fingerprint,
        sa.alias_fingerprint_key_version,
        sa.alias_fingerprint_schema_version,
        sa.aad_context,
        sa.created_at,
        sa.updated_at
    from public.secret_aliases sa
    where sa.owner_user_id = p_owner_user_id
    order by sa.created_at desc, sa.id
    limit p_limit offset p_offset;
end;
$$;

create function public.rpc_resolve_secret_alias(
    p_owner_user_id uuid,
    p_alias_fingerprint bytea
)
returns table (
    id uuid,
    secret_id uuid,
    alias_ciphertext bytea,
    alias_nonce bytea,
    alias_key_version integer,
    aad_context jsonb
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if p_owner_user_id is null
        or p_alias_fingerprint is null
        or octet_length(p_alias_fingerprint) <> 32
    then
        raise exception 'invalid_rpc_input' using errcode = '22023';
    end if;

    return query
    select sa.id,
        sa.secret_id,
        sa.alias_ciphertext,
        sa.alias_nonce,
        sa.alias_key_version,
        sa.aad_context
    from public.secret_aliases sa
    where sa.owner_user_id = p_owner_user_id
        and sa.alias_fingerprint = p_alias_fingerprint;
end;
$$;

comment on function public.rpc_create_secret_alias(
    uuid,
    uuid,
    uuid,
    uuid,
    bytea,
    bytea,
    integer,
    bytea,
    integer,
    integer,
    jsonb,
    timestamptz
) is
    'Creates an encrypted owner-scoped alias and records the success audit event in the same transaction.';
comment on function public.rpc_update_secret_alias(
    uuid,
    uuid,
    uuid,
    bytea,
    bytea,
    integer,
    bytea,
    integer,
    integer,
    jsonb
) is
    'Updates encrypted alias material for an existing alias without changing its canonical secret_id.';
comment on function public.rpc_delete_secret_alias(uuid, uuid, uuid) is
    'Deletes one encrypted alias and records the success audit event in the same transaction.';
comment on function public.rpc_list_secret_aliases(uuid, uuid, integer, integer) is
    'Returns encrypted aliases for one owner. Audit is appended by the SBC after successful decryption.';
comment on function public.rpc_resolve_secret_alias(uuid, bytea) is
    'Resolves one owner-scoped alias fingerprint to encrypted alias material without recording a standalone audit event.';

revoke execute on function public.rpc_create_secret_alias(
    uuid,
    uuid,
    uuid,
    uuid,
    bytea,
    bytea,
    integer,
    bytea,
    integer,
    integer,
    jsonb,
    timestamptz
) from public, anon, authenticated;
grant execute on function public.rpc_create_secret_alias(
    uuid,
    uuid,
    uuid,
    uuid,
    bytea,
    bytea,
    integer,
    bytea,
    integer,
    integer,
    jsonb,
    timestamptz
) to service_role;

revoke execute on function public.rpc_update_secret_alias(
    uuid,
    uuid,
    uuid,
    bytea,
    bytea,
    integer,
    bytea,
    integer,
    integer,
    jsonb
) from public, anon, authenticated;
grant execute on function public.rpc_update_secret_alias(
    uuid,
    uuid,
    uuid,
    bytea,
    bytea,
    integer,
    bytea,
    integer,
    integer,
    jsonb
) to service_role;

revoke execute on function public.rpc_delete_secret_alias(uuid, uuid, uuid)
    from public, anon, authenticated;
grant execute on function public.rpc_delete_secret_alias(uuid, uuid, uuid)
    to service_role;

revoke execute on function public.rpc_list_secret_aliases(uuid, uuid, integer, integer)
    from public, anon, authenticated;
grant execute on function public.rpc_list_secret_aliases(uuid, uuid, integer, integer)
    to service_role;

revoke execute on function public.rpc_resolve_secret_alias(uuid, bytea)
    from public, anon, authenticated;
grant execute on function public.rpc_resolve_secret_alias(uuid, bytea)
    to service_role;