pub(super) const DEFAULT_DOTENV_PATH: &str = ".env";
pub(super) const DEFAULT_LISTEN_ADDR: &str = "127.0.0.1:3000";
pub(super) const DEFAULT_AUDIT_FALLBACK_PATH: &str =
    "/var/lib/mipsorcu/audit-fallback-current.jsonl";
pub(super) const DEFAULT_SIEM_BUFFER_PATH: &str = "/var/lib/mipsorcu/siem-buffer-current.jsonl";
pub(super) const DEFAULT_AUDIT_RESEND_INTERVAL_SECONDS: u64 = 60;
pub(super) const DEFAULT_SIEM_RESEND_INTERVAL_SECONDS: u64 = 300;
pub(super) const DEFAULT_SIEM_LONG_FAILURE_THRESHOLD_SECONDS: u64 = 15 * 60;
pub(super) const DEFAULT_SIEM_BUFFER_MAX_BYTES: u64 = 100 * 1024 * 1024;
pub(super) const SIEM_BUFFER_MAX_BYTES_LIMIT: u64 = 1024 * 1024 * 1024;
pub(super) const DEFAULT_AUDIT_FALLBACK_ALERT_THRESHOLD_BYTES: u64 = 10 * 1024 * 1024;
pub(super) const DEFAULT_AUDIT_FALLBACK_ROTATE_SIZE_BYTES: u64 = 64 * 1024 * 1024;
pub(super) const DEFAULT_AUDIT_FALLBACK_ARCHIVE_RETENTION_DAYS: u64 = 90;
pub(super) const SECONDS_PER_DAY: u64 = 24 * 60 * 60;
pub(super) const DEFAULT_RESTORE_TEST_INTERVAL_SECONDS: u64 = 24 * 60 * 60;
pub(super) const DEFAULT_RESTORE_TEST_STARTUP_DELAY_SECONDS: u64 = 300;
pub(super) const DEFAULT_RESTORE_TEST_SAMPLE_LIMIT: u32 = 3;
pub(super) const DEFAULT_INTEGRITY_CHECK_INTERVAL_SECONDS: u64 = 24 * 60 * 60;
pub(super) const DEFAULT_INTEGRITY_CHECK_STARTUP_DELAY_SECONDS: u64 = 3900;
pub(super) const DEFAULT_JWKS_REFRESH_INTERVAL_SECONDS: u64 = 60 * 60;
pub(super) const DEFAULT_HEALTH_READINESS_POLL_INTERVAL_SECONDS: u64 = 30;
pub(super) const DEFAULT_OUTBOUND_HTTP_CONNECT_TIMEOUT_SECONDS: u64 = 5;
pub(super) const DEFAULT_OUTBOUND_HTTP_REQUEST_TIMEOUT_SECONDS: u64 = 20;
pub(super) const DEFAULT_HTTP_HANDLER_TIMEOUT_SECONDS: u64 = 75;
pub(super) const DEFAULT_HTTP_RATE_LIMIT_REQUESTS: u64 = 300;
pub(super) const DEFAULT_HTTP_RATE_LIMIT_WINDOW_SECONDS: u64 = 60;
pub(super) const DEFAULT_SCHEDULER_STARTUP_DELAY_SECONDS: u64 = 30;
pub(super) const DEFAULT_SCHEDULER_POLL_INTERVAL_SECONDS: u64 = 60 * 60;
pub(super) const DEFAULT_SCHEDULER_MONTHLY_DAY: u8 = 1;
pub(super) const DEFAULT_SCHEDULER_MONTHLY_HOUR_UTC: u8 = 3;
pub(super) const DEFAULT_SCHEDULER_QUARTERLY_HOUR_UTC: u8 = 4;
pub(super) const DEFAULT_SCHEDULER_DAILY_HOUR_UTC: u8 = 4;
pub(super) const DEFAULT_SCHEDULER_ENVELOPE_MIGRATION_BATCH_SIZE: u32 = 100;
pub(super) const DEFAULT_SCHEDULER_ENVELOPE_MIGRATION_MAX_BATCHES: u32 = 10;
pub(super) const DEFAULT_SCHEDULER_LOCAL_ARCHIVE_DIR: &str = "/var/lib/mipsorcu/scheduler-archive";

pub(super) const ENV_LISTEN_ADDR: &str = "MIPSORCU_LISTEN_ADDR";
pub(super) const ENV_MASTER_KEY: &str = "MIPSORCU_MASTER_KEY";
pub(super) const ENV_KEY_VERSION: &str = "MIPSORCU_KEY_VERSION";
pub(super) const ENV_MASTER_KEY_VERSION: &str = "MIPSORCU_MASTER_KEY_VERSION";
pub(super) const ENV_ALIAS_ENCRYPTION_KEY: &str = "MIPSORCU_ALIAS_ENCRYPTION_KEY";
pub(super) const ENV_ALIAS_ENCRYPTION_KEY_VERSION: &str = "MIPSORCU_ALIAS_ENCRYPTION_KEY_VERSION";
pub(super) const ENV_ALIAS_FINGERPRINT_KEY: &str = "MIPSORCU_ALIAS_FINGERPRINT_KEY";
pub(super) const ENV_ALIAS_FINGERPRINT_KEY_VERSION: &str = "MIPSORCU_ALIAS_FINGERPRINT_KEY_VERSION";
pub(super) const ENV_ACTIVE_KEY_VERSION: &str = "MIPSORCU_ACTIVE_KEY_VERSION";
pub(super) const ENV_MASTER_KEY_DIR: &str = "MIPSORCU_MASTER_KEY_DIR";
pub(super) const ENV_SUPABASE_URL: &str = "MIPSORCU_SUPABASE_URL";
pub(super) const ENV_SUPABASE_SERVICE_ROLE_KEY: &str = "MIPSORCU_SUPABASE_SERVICE_ROLE_KEY";
pub(super) const ENV_SUPABASE_PUBLISHABLE_KEY: &str = "MIPSORCU_SUPABASE_PUBLISHABLE_KEY";
pub(super) const ENV_LEDGER_SIGNING_KEY: &str = "MIPSORCU_LEDGER_SIGNING_KEY";
pub(super) const ENV_LEDGER_SIGNATURE_KEY_VERSION: &str = "MIPSORCU_LEDGER_SIGNATURE_KEY_VERSION";
pub(super) const ENV_JWT_ISSUER: &str = "MIPSORCU_JWT_ISSUER";
pub(super) const ENV_JWT_AUDIENCE: &str = "MIPSORCU_JWT_AUDIENCE";
pub(super) const ENV_JWKS_URL: &str = "MIPSORCU_JWKS_URL";
pub(super) const ENV_AUDIT_FALLBACK_PATH: &str = "MIPSORCU_AUDIT_FALLBACK_PATH";
pub(super) const ENV_SIEM_BUFFER_PATH: &str = "MIPSORCU_SIEM_BUFFER_PATH";
pub(super) const ENV_SIEM_BUFFER_MAX_BYTES: &str = "MIPSORCU_SIEM_BUFFER_MAX_BYTES";
pub(super) const ENV_AUDIT_RESEND_INTERVAL_SECONDS: &str = "MIPSORCU_AUDIT_RESEND_INTERVAL_SECONDS";
pub(super) const ENV_SIEM_RESEND_INTERVAL_SECONDS: &str = "MIPSORCU_SIEM_RESEND_INTERVAL_SECONDS";
pub(super) const ENV_SIEM_LONG_FAILURE_THRESHOLD_SECONDS: &str =
    "MIPSORCU_SIEM_LONG_FAILURE_THRESHOLD_SECONDS";
pub(super) const ENV_SIEM_EXPORTER: &str = "MIPSORCU_SIEM_EXPORTER";
pub(super) const ENV_SIEM_OTLP_ENDPOINT: &str = "MIPSORCU_SIEM_OTLP_ENDPOINT";
pub(super) const ENV_SIEM_OTLP_AUTH_TOKEN: &str = "MIPSORCU_SIEM_OTLP_AUTH_TOKEN";
pub(super) const ENV_SIEM_SPLUNK_HEC_URL: &str = "MIPSORCU_SIEM_SPLUNK_HEC_URL";
pub(super) const ENV_SIEM_SPLUNK_HEC_TOKEN: &str = "MIPSORCU_SIEM_SPLUNK_HEC_TOKEN";
pub(super) const ENV_INCIDENT_NOTIFIER: &str = "MIPSORCU_INCIDENT_NOTIFIER";
pub(super) const ENV_INCIDENT_WEBHOOK_URL: &str = "MIPSORCU_INCIDENT_WEBHOOK_URL";
pub(super) const ENV_INCIDENT_WEBHOOK_SECRET: &str = "MIPSORCU_INCIDENT_WEBHOOK_SECRET";

pub(super) const INCIDENT_WEBHOOK_SECRET_MIN_BYTES: usize = 32;
pub(super) const ENV_AUDIT_FALLBACK_ALERT_THRESHOLD_BYTES: &str =
    "MIPSORCU_AUDIT_FALLBACK_ALERT_THRESHOLD_BYTES";
pub(super) const ENV_AUDIT_FALLBACK_ROTATE_SIZE_BYTES: &str =
    "MIPSORCU_AUDIT_FALLBACK_ROTATE_SIZE_BYTES";
pub(super) const ENV_AUDIT_FALLBACK_ARCHIVE_DIR: &str = "MIPSORCU_AUDIT_FALLBACK_ARCHIVE_DIR";
pub(super) const ENV_AUDIT_FALLBACK_ARCHIVE_AUTO_DELETE_ENABLED: &str =
    "MIPSORCU_AUDIT_FALLBACK_ARCHIVE_AUTO_DELETE_ENABLED";
pub(super) const ENV_AUDIT_FALLBACK_ARCHIVE_RETENTION_DAYS: &str =
    "MIPSORCU_AUDIT_FALLBACK_ARCHIVE_RETENTION_DAYS";
pub(super) const ENV_RESTORE_TEST_INTERVAL_SECONDS: &str = "MIPSORCU_RESTORE_TEST_INTERVAL_SECONDS";
pub(super) const ENV_RESTORE_TEST_STARTUP_DELAY_SECONDS: &str =
    "MIPSORCU_RESTORE_TEST_STARTUP_DELAY_SECONDS";
pub(super) const ENV_RESTORE_TEST_SAMPLE_LIMIT: &str = "MIPSORCU_RESTORE_TEST_SAMPLE_LIMIT";
pub(super) const ENV_INTEGRITY_CHECK_INTERVAL_SECONDS: &str =
    "MIPSORCU_INTEGRITY_CHECK_INTERVAL_SECONDS";
pub(super) const ENV_INTEGRITY_CHECK_STARTUP_DELAY_SECONDS: &str =
    "MIPSORCU_INTEGRITY_CHECK_STARTUP_DELAY_SECONDS";
pub(super) const ENV_JWKS_REFRESH_INTERVAL_SECONDS: &str = "MIPSORCU_JWKS_REFRESH_INTERVAL_SECONDS";
pub(super) const ENV_HEALTH_READINESS_POLL_INTERVAL_SECONDS: &str =
    "MIPSORCU_HEALTH_READINESS_POLL_INTERVAL_SECONDS";
pub(super) const ENV_OUTBOUND_HTTP_CONNECT_TIMEOUT_SECONDS: &str =
    "MIPSORCU_OUTBOUND_HTTP_CONNECT_TIMEOUT_SECONDS";
pub(super) const ENV_OUTBOUND_HTTP_REQUEST_TIMEOUT_SECONDS: &str =
    "MIPSORCU_OUTBOUND_HTTP_REQUEST_TIMEOUT_SECONDS";
pub(super) const ENV_HTTP_HANDLER_TIMEOUT_SECONDS: &str = "MIPSORCU_HTTP_HANDLER_TIMEOUT_SECONDS";
pub(super) const ENV_HTTP_RATE_LIMIT_REQUESTS: &str = "MIPSORCU_HTTP_RATE_LIMIT_REQUESTS";
pub(super) const ENV_HTTP_RATE_LIMIT_WINDOW_SECONDS: &str =
    "MIPSORCU_HTTP_RATE_LIMIT_WINDOW_SECONDS";
pub(super) const ENV_SCHEDULER_ENABLED: &str = "MIPSORCU_SCHEDULER_ENABLED";
pub(super) const ENV_SCHEDULER_STARTUP_DELAY_SECONDS: &str =
    "MIPSORCU_SCHEDULER_STARTUP_DELAY_SECONDS";
pub(super) const ENV_SCHEDULER_STARTUP_DELAY_SEC: &str = "MIPSORCU_SCHEDULER_STARTUP_DELAY_SEC";
pub(super) const ENV_SCHEDULER_POLL_INTERVAL_SECONDS: &str =
    "MIPSORCU_SCHEDULER_POLL_INTERVAL_SECONDS";
pub(super) const ENV_SCHEDULER_MONTHLY_DAY: &str = "MIPSORCU_SCHEDULER_MONTHLY_DAY";
pub(super) const ENV_SCHEDULER_MONTHLY_HOUR_UTC: &str = "MIPSORCU_SCHEDULER_MONTHLY_HOUR_UTC";
pub(super) const ENV_SCHEDULER_QUARTERLY_HOUR_UTC: &str = "MIPSORCU_SCHEDULER_QUARTERLY_HOUR_UTC";
pub(super) const ENV_SCHEDULER_DAILY_HOUR_UTC: &str = "MIPSORCU_SCHEDULER_DAILY_HOUR_UTC";
pub(super) const ENV_SCHEDULER_ENVELOPE_MIGRATION_BATCH_SIZE: &str =
    "MIPSORCU_SCHEDULER_ENVELOPE_MIGRATION_BATCH_SIZE";
pub(super) const ENV_SCHEDULER_ENVELOPE_MIGRATION_MAX_BATCHES: &str =
    "MIPSORCU_SCHEDULER_ENVELOPE_MIGRATION_MAX_BATCHES";
pub(super) const ENV_SCHEDULER_LOCAL_ARCHIVE_DIR: &str = "MIPSORCU_SCHEDULER_LOCAL_ARCHIVE_DIR";

pub(super) const SCHEDULER_ENVELOPE_MIGRATION_BATCH_SIZE_MAX: u32 = 1_000;
